fix(dispatch): disable caching in CDN
adobe/helix-dispatch pull request #329
Opened 2020-08-19 07:50 UTC by tripodsan

see https://github.com/adobe/helix-pages/issues/424

2020-08-19 10:01 UTC, trieloff commented
As it stands right now, this is a breaking change that disables caching on all sites, not just helix pages.

2020-08-19 10:02 UTC, trieloff requested changes
Don't disable caching for all sites, keep the selectivity.

2020-08-20 02:08 UTC, tripodsan commented
> Don't disable caching for all sites, keep the selectivity.

2020-08-20 02:09 UTC, tripodsan commented
> As it stands right now, this is a breaking change that disables caching on all sites, not just helix pages.

right now, we don't have to support any other site than helix-pages....so it doesn't really matter.....

2020-08-20 07:23 UTC, stefan-guggisberg commented on src/index.js
> +    // if requested, disable caching in the CND (private) and
```suggestion
    // if requested, disable caching in the CDN (private) and
```

2020-08-20 07:25 UTC, trieloff approved these changes

2020-08-21 01:33 UTC, merged